### ISSUE TITLE
PHP 7 deprecated notice

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/static_content_blocks#3]
I'm seeing this notice when I switch from GoExplore! to a different theme...

> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Theme_StaticBlock_Widget has a deprecated constructor in /xxx/xxx/xxx/parallelus-go-explore/wp-content/themes/parallelus-go-explore/extensions/theme-utilities/post-type-static-block.php on line 345

**Comment by lesninsky** [comment]
In the repo "static_content_blocks" this issue has already been fixed, so I have made fixes in the file ..parallelus-go-explore/extensions/theme-utilities/post-type-static-block.php - commit https://github.com/parallelus/GoExplore/commit/96d45ad133805f10a88256307bba7cfaf51f75c2

**Comment by jeffwalker99** [comment]
I saw that notice with v1.0.3 of the Static Content Blocks plugin.

We shouldn't be fixing Static Content Blocks plugin issues in other repos, only in this repo. When themes that include this plugin are updated we will include the latest version in the theme updates.

**Comment by lesninsky** [comment]
In the repo "static_content_blocks" this issue has already been fixed.
I have fixed the issue in the file, where notice is arising -
 _`in /xxx/xxx/xxx/parallelus-go-explore/wp-content/themes/parallelus-go-explore/extensions/theme-utilities/post-type-static-block.php on line 345`_

I am not completely clear if I should revert this commit - https://github.com/parallelus/GoExplore/commit/96d45ad133805f10a88256307bba7cfaf51f75c2  ?

**Comment by jeffwalker99** [comment]
Oh! Why is that code there in the theme when static blocks are added using the Static Content Blocks plugin?

@parallelus Is this file needed? Should we remove it from GoExplore!?

**Comment by jeffwalker99** [comment]
Oh! That file is in the FrontRunner theme too!

**Comment by jeffwalker99** [comment]
And Caliber!

**Comment by parallelus** [comment]
The static blocks are added in the theme AND as a plugin. The reason they are a plugin is because they create a custom post type and so it's required by Envato that they be a plugin. They are also included in the theme because not everyone wants to enable a bunch of plugins when they activate a new theme. If they don't activate the plugin and they try to import demo content, it won't import those static block elements. Also, some features of the theme such as headers and footers may not work in some themes without the Static Blocks. So, we're including them in two ways to ensure the theme works and we comply with the Envato requirements too.

To update the theme you just need to copy the one file from the plugin into the extension folder. The plugin install file is updated the normal way.

**Comment by jeffwalker99** [comment]
So when I update the 'static_content_blocks.zip' to a theme to update that plugin I also have to remember to update that 'post-type-static-block.php' file with the latest version of that file from the plugin. Yes?

**Comment by parallelus** [comment]
Yes
